version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          first: Install bundler
          command: gem install bundler:2.1.4
          name: Which bundler?
          check: bundle -v
      - ruby/bundle-install
